name: 🚀 Deploy - TrinityKit

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 18.17.1
      - run: npm install -g yarn
      - run: yarn install --frozen-lockfile
      - name: Set up environment variables
        run: echo "WORDPRESS_URL=$WORDPRESS_URL" >> $GITHUB_ENV
      - run: yarn build