name: 🚀 Deploy - TrinityKit CMS

on:
  push:
    branches:
      - master

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🛠️ Build project and create .htaccess
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - run: npm install -g yarn
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - run: |
          echo "RewriteEngine On" > out/.htaccess
          echo "RewriteBase /" >> out/.htaccess
          # Adicione mais regras do .htaccess conforme necessário
      - name: 📂 Arquivos modificados
        run: git status
