on:
  push:
    branches:
      - master

name: 🚀 Deploy - TrinityKit CMS

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    
    - name: 🛠️ Build project and create .htaccess
      uses: actions/setup-node@v1
      with:
        node-version: 12
      steps:
        - run: npm install -g yarn
        - run: yarn install --frozen-lockfile
        - run: yarn build
        - run: |
            echo "RewriteEngine On" > out/.htaccess
            echo "RewriteBase /" >> out/.htaccess
            # Adicione mais regras do .htaccess conforme necessário

    - name: 🚚 Get latest code
      uses: actions/checkout@v3

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_HOST }}
        username: ${{ secrets.FTP_LOGIN }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: /hml.thetrinityweb.com.br/
        local-dir: out/
