name: 🚀 Deploy - TrinityKit

on:
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Setup Node.js environment
        uses: actions/setup-node@v1
        with:
          node-version: '18.17.1'

      - name: Build with secrets variables
        run: |
          npm install -g yarn
          yarn install --frozen-lockfile
          yarn build
        env:
          WORDPRESS_URL: ${{ secrets.WORDPRESS_URL }}

      - name: Create .htaccess file
        run: |
          echo "# Disable directory indexes and MultiViews" >> out/.htaccess
          echo "Options -Indexes -MultiViews" >> out/.htaccess
          echo "" >> out/.htaccess
          echo "# Prevent mod_dir appending a slash to directory requests" >> out/.htaccess
          echo "DirectorySlash Off" >> out/.htaccess
          echo "" >> out/.htaccess
          echo "RewriteEngine On" >> out/.htaccess
          echo "" >> out/.htaccess
          echo "# Rewrite /foo to /foo.html if it exists" >> out/.htaccess
          echo "RewriteCond %{DOCUMENT_ROOT}%{REQUEST_URI}.html -f" >> out/.htaccess
          echo "RewriteRule !\.\w{2,4}$ %{REQUEST_URI}.html [L]" >> out/.htaccess
          echo "" >> out/.htaccess
          echo "# Otherwise, rewrite /foo to /foo/index.html if it exists" >> out/.htaccess
          echo "RewriteCond %{DOCUMENT_ROOT}%{REQUEST_URI}/index.html -f" >> out/.htaccess
          echo "RewriteRule !\.\w{2,4}$ %{REQUEST_URI}/index.html [L]" >> out/.htaccess
          echo "# Redirecionar todas as páginas 404 para /404" >> out/.htaccess
          echo "ErrorDocument 404 /404" >> out/.htaccess
        
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Deploy to FTP Server
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
            server: ${{secrets.FTP_HOST}}
            username: ${{ secrets.FTP_LOGIN }}
            password: ${{ secrets.FTP_PASSWORD }}
            local-dir: out/
            server-dir: /hml.thetrinityweb.com.br/